language: go
go:
    - 1.8
    - 1.9
    - tip

install:
  - go get github.com/golang/lint/golint
  - go get -t ./...

script:
  - golint $(go list ./... | grep -v /vendor/)
  - go test ./...

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash